# fly.toml app configuration file generated for rfbalisson-wispy-wildflower-3494 on 2025-07-24T16:58:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rfbalisson-wispy-wildflower-3494'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
